apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: microservices
data:
  postgresql.conf: |
    wal_level = replica
    max_wal_senders = 10
    max_replication_slots = 10
    hot_standby = on
