apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-list-service
  namespace: microservices
spec:
  replicas: 2

  selector:
    matchLabels:
      app: user-list-service

  template:
    metadata:
      labels:
        app: user-list-service

    spec:
      containers:
        - name: user-list-service
          image: project-user-list-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8002
