apiVersion: v1
kind: Service
metadata:
  name: user-list-service
  namespace: microservices
spec:
  selector:
    app: user-list-service
  ports:
    - port: 8002
      targetPort: 8002
  type: ClusterIP
